eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  eureka:
    enabled: true
  routes:
    api-a:
      path: /api-a/**
      serviceId: server-one
    api-b:
      path: /api-b/**
      serviceId: server-two
  strip-prefix: false

#ribbon:
#  eureka:
#    enabled: false
